import { z } from 'zod';
export declare const JournalEntryType: {
    readonly MANUAL: "manual";
    readonly AUTOMATIC: "automatic";
    readonly ADJUSTMENT: "adjustment";
    readonly OPENING: "opening";
    readonly CLOSING: "closing";
    readonly REVERSAL: "reversal";
};
export type JournalEntryType = typeof JournalEntryType[keyof typeof JournalEntryType];
export declare const JournalEntryStatus: {
    readonly DRAFT: "draft";
    readonly PENDING: "pending";
    readonly APPROVED: "approved";
    readonly POSTED: "posted";
    readonly CANCELLED: "cancelled";
};
export type JournalEntryStatus = typeof JournalEntryStatus[keyof typeof JournalEntryStatus];
export declare const TransactionOrigin: {
    readonly SALE: "sale";
    readonly PURCHASE: "purchase";
    readonly ADJUSTMENT: "adjustment";
    readonly TRANSFER: "transfer";
    readonly PAYMENT: "payment";
    readonly COLLECTION: "collection";
    readonly OPENING: "opening";
    readonly CLOSING: "closing";
    readonly OTHER: "other";
};
export type TransactionOrigin = typeof TransactionOrigin[keyof typeof TransactionOrigin];
export interface PaymentScheduleItem {
    sequence: number;
    days: number;
    percentage: number;
    amount: number;
    payment_date: string;
    description: string;
}
export interface JournalEntryLine {
    id: string;
    journal_entry_id: string;
    account_id: string;
    account_code?: string;
    account_name?: string;
    debit_amount: string;
    credit_amount: string;
    description?: string;
    reference?: string;
    third_party_id?: string;
    cost_center_id?: string;
    line_number: number;
    created_at: string;
    updated_at: string;
    third_party_code?: string;
    third_party_name?: string;
    third_party_document_type?: string;
    third_party_document_number?: string;
    third_party_tax_id?: string;
    third_party_email?: string;
    third_party_phone?: string;
    third_party_address?: string;
    third_party_city?: string;
    third_party_type?: 'customer' | 'supplier' | 'employee' | 'other';
    cost_center_code?: string;
    cost_center_name?: string;
    payment_terms_id?: string;
    payment_terms_code?: string;
    payment_terms_name?: string;
    payment_terms_description?: string;
    invoice_date?: string;
    due_date?: string;
    effective_invoice_date?: string;
    effective_due_date?: string;
    product_id?: string;
    product_code?: string;
    product_name?: string;
    product_type?: string;
    product_measurement_unit?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    discount_amount?: string;
    tax_percentage?: string;
    tax_amount?: string;
    subtotal_before_discount?: string;
    effective_unit_price?: string;
    total_discount?: string;
    subtotal_after_discount?: string;
    net_amount?: string;
    gross_amount?: string;
    amount?: string;
    movement_type?: 'debit' | 'credit';
    payment_schedule?: PaymentScheduleItem[];
}
export interface JournalEntry {
    id: string;
    number: string;
    reference?: string;
    description: string;
    entry_type: JournalEntryType;
    transaction_origin?: TransactionOrigin;
    entry_date: string;
    earliest_due_date?: string;
    posting_date?: string;
    status: JournalEntryStatus;
    total_debit: string;
    total_credit: string;
    created_by_id: string;
    approved_by_id?: string;
    posted_by_id?: string;
    cancelled_by_id?: string;
    created_at: string;
    updated_at: string;
    approved_at?: string;
    posted_at?: string;
    cancelled_at?: string;
    notes?: string;
    external_reference?: string;
    lines: JournalEntryLine[];
    created_by_name?: string;
    approved_by_name?: string;
    posted_by_name?: string;
    cancelled_by_name?: string;
    is_balanced?: boolean;
    can_be_posted?: boolean;
    can_be_edited?: boolean;
}
export declare const journalEntryLineCreateSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
    account_id: z.ZodString;
    debit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
    credit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
    description: z.ZodOptional<z.ZodString>;
    reference: z.ZodOptional<z.ZodString>;
    third_party_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    cost_center_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    payment_terms_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    invoice_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    due_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    product_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    quantity: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    unit_price: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    discount_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    discount_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    tax_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    tax_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}, "strip", z.ZodTypeAny, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}, {
    description?: string;
    reference?: string;
    debit_amount?: string | number;
    credit_amount?: string | number;
    invoice_date?: string;
    due_date?: string;
    third_party_id?: string;
    payment_terms_id?: string;
    tax_amount?: string;
    discount_amount?: string;
    cost_center_id?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    account_id?: string;
    tax_percentage?: string;
}>;
export declare const journalEntryCreateSchema: z.ZodEffects<z.ZodObject<{
    reference: z.ZodOptional<z.ZodString>;
    description: z.ZodString;
    entry_type: z.ZodEnum<["manual", "automatic", "adjustment", "opening", "closing", "reversal"]>;
    transaction_origin: z.ZodOptional<z.ZodEnum<["sale", "purchase", "adjustment", "transfer", "payment", "collection", "opening", "closing", "other"]>>;
    entry_date: z.ZodEffects<z.ZodString, string, string>;
    notes: z.ZodOptional<z.ZodString>;
    external_reference: z.ZodOptional<z.ZodString>;
    lines: z.ZodArray<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
        account_id: z.ZodString;
        debit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
        credit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
        description: z.ZodOptional<z.ZodString>;
        reference: z.ZodOptional<z.ZodString>;
        third_party_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        cost_center_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        payment_terms_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        invoice_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        due_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        product_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        quantity: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        unit_price: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        discount_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        discount_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        tax_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        tax_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    }, "strip", z.ZodTypeAny, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
    transaction_origin?: "other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection";
}, {
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
    transaction_origin?: "other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection";
}>, {
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
    transaction_origin?: "other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection";
}, {
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
    transaction_origin?: "other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection";
}>;
export declare const journalEntryUpdateSchema: z.ZodObject<{
    id: z.ZodString;
    reference: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    entry_type: z.ZodOptional<z.ZodEnum<["manual", "automatic", "adjustment", "opening", "closing", "reversal"]>>;
    entry_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    notes: z.ZodOptional<z.ZodString>;
    external_reference: z.ZodOptional<z.ZodString>;
    lines: z.ZodOptional<z.ZodArray<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
        account_id: z.ZodString;
        debit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
        credit_amount: z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodNumber]>;
        description: z.ZodOptional<z.ZodString>;
        reference: z.ZodOptional<z.ZodString>;
        third_party_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        cost_center_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        payment_terms_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        invoice_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        due_date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        product_id: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        quantity: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        unit_price: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        discount_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        discount_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        tax_percentage: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
        tax_amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    }, "strip", z.ZodTypeAny, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }, {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }>, "many">>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
}, {
    id?: string;
    description?: string;
    notes?: string;
    entry_date?: string;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    lines?: {
        description?: string;
        reference?: string;
        debit_amount?: string | number;
        credit_amount?: string | number;
        invoice_date?: string;
        due_date?: string;
        third_party_id?: string;
        payment_terms_id?: string;
        tax_amount?: string;
        discount_amount?: string;
        cost_center_id?: string;
        product_id?: string;
        quantity?: string;
        unit_price?: string;
        discount_percentage?: string;
        account_id?: string;
        tax_percentage?: string;
    }[];
    external_reference?: string;
}>;
export declare const journalEntryFiltersSchema: z.ZodObject<{
    skip: z.ZodOptional<z.ZodNumber>;
    limit: z.ZodOptional<z.ZodNumber>;
    entry_type: z.ZodOptional<z.ZodEnum<["manual", "automatic", "adjustment", "opening", "closing", "reversal"]>>;
    status: z.ZodOptional<z.ZodEnum<["draft", "pending", "approved", "posted", "cancelled"]>>;
    transaction_origin: z.ZodOptional<z.ZodArray<z.ZodEnum<["sale", "purchase", "adjustment", "transfer", "payment", "collection", "opening", "closing", "other"]>, "many">>;
    date_from: z.ZodOptional<z.ZodString>;
    date_to: z.ZodOptional<z.ZodString>;
    search: z.ZodOptional<z.ZodString>;
    account_id: z.ZodOptional<z.ZodString>;
    created_by_id: z.ZodOptional<z.ZodString>;
    reference: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    search?: string;
    status?: "pending" | "cancelled" | "posted" | "draft" | "approved";
    skip?: number;
    limit?: number;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    created_by_id?: string;
    date_from?: string;
    date_to?: string;
    account_id?: string;
    transaction_origin?: ("other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection")[];
}, {
    search?: string;
    status?: "pending" | "cancelled" | "posted" | "draft" | "approved";
    skip?: number;
    limit?: number;
    reference?: string;
    entry_type?: "manual" | "adjustment" | "automatic" | "opening" | "closing" | "reversal";
    created_by_id?: string;
    date_from?: string;
    date_to?: string;
    account_id?: string;
    transaction_origin?: ("other" | "sale" | "purchase" | "adjustment" | "transfer" | "opening" | "closing" | "payment" | "collection")[];
}>;
export type JournalEntryCreate = z.infer<typeof journalEntryCreateSchema>;
export type JournalEntryUpdate = z.infer<typeof journalEntryUpdateSchema>;
export type JournalEntryLineCreate = z.infer<typeof journalEntryLineCreateSchema>;
export type JournalEntryFilters = z.infer<typeof journalEntryFiltersSchema>;
export interface JournalEntryFormData {
    reference?: string;
    description: string;
    entry_type: JournalEntryType;
    transaction_origin?: TransactionOrigin;
    entry_date: string;
    notes?: string;
    external_reference?: string;
    third_party_id?: string;
    cost_center_id?: string;
    payment_terms_id?: string;
    invoice_date?: string;
    due_date?: string;
    lines: JournalEntryLineFormData[];
}
export interface JournalEntryLineFormData {
    account_id: string;
    account_code?: string;
    account_name?: string;
    debit_amount: string;
    credit_amount: string;
    description?: string;
    reference?: string;
    third_party_id?: string;
    cost_center_id?: string;
    payment_terms_id?: string;
    invoice_date?: string;
    due_date?: string;
    product_id?: string;
    quantity?: string;
    unit_price?: string;
    discount_percentage?: string;
    discount_amount?: string;
    tax_percentage?: string;
    tax_amount?: string;
}
export declare const JOURNAL_ENTRY_TYPE_LABELS: Record<JournalEntryType, string>;
export declare const JOURNAL_ENTRY_STATUS_LABELS: Record<JournalEntryStatus, string>;
export declare const JOURNAL_ENTRY_TYPE_DESCRIPTIONS: Record<JournalEntryType, string>;
export declare const TransactionOriginLabels: Record<TransactionOrigin, string>;
export declare const getTransactionOriginColor: (origin?: TransactionOrigin) => string;
export declare const isProductTransaction: (origin?: TransactionOrigin) => boolean;
export declare const validateTransactionOriginCoherence: (origin?: TransactionOrigin, lines?: {
    debit_amount: string;
    credit_amount: string;
}[]) => {
    valid: boolean;
    message?: string;
};
export interface JournalEntryStatistics {
    total_entries: number;
    total_by_status: Record<JournalEntryStatus, number>;
    total_by_type: Record<JournalEntryType, number>;
    total_amount: string;
    entries_this_month: number;
    pending_approval: number;
}
export interface JournalEntryBalance {
    total_debit: string;
    total_credit: string;
    difference: string;
    is_balanced: boolean;
}
export interface JournalEntryListResponse {
    items: JournalEntry[];
    total: number;
    page: number;
    pages: number;
    has_next: boolean;
    has_prev: boolean;
}
export interface JournalEntryOperationResponse {
    success: boolean;
    message: string;
    journal_entry?: JournalEntry;
}
export interface BulkJournalEntryRequest {
    journal_entry_ids: string[];
    reason: string;
    force?: boolean;
}
export interface BulkJournalEntryApprove extends BulkJournalEntryRequest {
    approved_by_id?: string;
    force_approve?: boolean;
}
export interface BulkJournalEntryPost extends BulkJournalEntryRequest {
    posted_by_id?: string;
    force_post?: boolean;
}
export interface BulkJournalEntryCancel extends BulkJournalEntryRequest {
    cancelled_by_id?: string;
    force_cancel?: boolean;
}
export interface BulkJournalEntryReverse extends BulkJournalEntryRequest {
    reversal_date: string;
    reversed_by_id?: string;
    force_reverse?: boolean;
}
export interface BulkJournalEntryResetToDraft extends BulkJournalEntryRequest {
    reset_by_id?: string;
    force_reset?: boolean;
}
export interface JournalEntryOperationValidation {
    journal_entry_id: string;
    journal_entry_number: string;
    journal_entry_description: string;
    current_status: JournalEntryStatus;
    can_approve?: boolean;
    can_post?: boolean;
    can_cancel?: boolean;
    can_reverse?: boolean;
    can_reset?: boolean;
    errors: string[];
    warnings: string[];
}
export interface JournalEntryApproveValidation extends JournalEntryOperationValidation {
    can_approve: boolean;
}
export interface JournalEntryPostValidation extends JournalEntryOperationValidation {
    can_post: boolean;
}
export interface JournalEntryCancelValidation extends JournalEntryOperationValidation {
    can_cancel: boolean;
}
export interface JournalEntryReverseValidation extends JournalEntryOperationValidation {
    can_reverse: boolean;
    reversal_date: string;
}
export interface JournalEntryResetToDraftValidation extends JournalEntryOperationValidation {
    can_reset: boolean;
}
export interface BulkJournalEntryOperationResult {
    operation_id: string;
    total_requested: number;
    total_processed: number;
    total_failed: number;
    execution_time_ms: number;
    processed_entries: JournalEntryOperationValidation[];
    failed_entries: JournalEntryOperationValidation[];
    operation_summary: {
        reason: string;
        executed_by: string;
        executed_at: string;
    };
}
export interface BulkJournalEntryApproveResult extends BulkJournalEntryOperationResult {
    total_approved: number;
    approved_entries: JournalEntryApproveValidation[];
}
export interface BulkJournalEntryPostResult extends BulkJournalEntryOperationResult {
    total_posted: number;
    posted_entries: JournalEntryPostValidation[];
}
export interface BulkJournalEntryCancelResult extends BulkJournalEntryOperationResult {
    total_cancelled: number;
    cancelled_entries: JournalEntryCancelValidation[];
}
export interface BulkJournalEntryReverseResult extends BulkJournalEntryOperationResult {
    total_reversed: number;
    reversed_entries: JournalEntryReverseValidation[];
    created_reversal_entries: JournalEntry[];
}
export interface BulkJournalEntryResetResult extends BulkJournalEntryOperationResult {
    total_reset: number;
    reset_entries: JournalEntryResetToDraftValidation[];
}
export interface BulkJournalEntryDeleteResult extends BulkJournalEntryOperationResult {
    total_deleted: number;
    deleted_entries: JournalEntryDeleteValidation[];
    warnings?: string[];
}
export interface BulkJournalEntryDelete {
    journal_entry_ids: string[];
    force_delete?: boolean;
    reason?: string;
}
export interface JournalEntryDeleteValidation {
    journal_entry_id: string;
    journal_entry_number: string;
    journal_entry_description: string;
    status: JournalEntryStatus;
    can_delete: boolean;
    errors: string[];
    warnings: string[];
}
export interface JournalEntryLineBackend {
    account_id: string;
    description?: string;
    debit_amount: number;
    credit_amount: number;
    third_party_id?: string;
    cost_center_id?: string;
    reference?: string;
    product_id?: string;
    quantity?: number;
    unit_price?: number;
    discount_percentage?: number;
    discount_amount?: number;
    tax_percentage?: number;
    tax_amount?: number;
    payment_terms_id?: string;
    invoice_date?: string;
    due_date?: string;
}
export interface JournalEntryBackend {
    entry_date: string;
    reference?: string;
    description: string;
    entry_type: JournalEntryType;
    transaction_origin?: TransactionOrigin;
    notes?: string;
    lines: JournalEntryLineBackend[];
}
